name: Build Cardex Android AAB

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Android SDK
  uses: android-actions/setup-android@v4
  with:
    packages: 'platform-tools'

      - name: Add Android platform
        run: npx cap add android

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Build AAB
        working-directory: android
        run: ./gradlew bundleRelease
        
      - name: Generar APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: cardex-apk
          path: android/app/build/outputs/apk/debug/*.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: cardex-release-aab
          path: android/app/build/outputs/bundle/release/*.aab
